### ISSUE TITLE
Errore Message: no such element: Unable to locate element: {"method":"partial link text","selector":"Sconto del 50%"}

### ISSUE THREAD

**Issue by Raffy142** [albertopasqualetto/amazon-deals-telegram-bot#7]
Ciao, è da un po’ che sta dando questo tipo di errore, hai per caso qualche soluzione?
Ti ringrazio in anticipo

Starting taking all urls
Message: no such element: Unable to locate element: {"method":"partial link text","selector":"Sconto del 50%"}
  (Session info: chrome-headless-shell=125.0.6422.141); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x556ce142ae3a <unknown>
#1 0x556ce111445c <unknown>
#2 0x556ce11605b5 <unknown>
#3 0x556ce1160671 <unknown>
#4 0x556ce11a4f14 <unknown>
#5 0x556ce11834dd <unknown>
#6 0x556ce11a22cc <unknown>
#7 0x556ce1183253 <unknown>
#8 0x556ce11531c7 <unknown>
#9 0x556ce1153b3e <unknown>
#10 0x556ce13f127b <unknown>
#11 0x556ce13f5327 <unknown>
#12 0x556ce13dddae <unknown>
#13 0x556ce13f5df2 <unknown>
#14 0x556ce13c274f <unknown>
#15 0x556ce141a128 <unknown>
#16 0x556ce141a2fb <unknown>
#17 0x556ce1429f6c <unknown>
#18 0x7fb3c022dac3 <unknown>

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/amazon-deals-telegram-bot/amazon-deals-telegram-bot/__main__.py", line 96, in <module>
    selected_product_info, already_sent_product_ids = get_random_product_info(deals_ids, already_sent_product_ids)
TypeError: cannot unpack non-iterable NoneType object

**Comment by albertopasqualetto** [comment]
Ciao @Raffy142 , sì, dev'esserci stata una modifica nelle pagine amazon circa un mese fa, infatti non funziona più nemmeno la nostra istanza.

Al momento personalmente non ho il tempo di occuparmi di rivedere il codice.

Grazie @GoukaMekkyaku per il possibile fix, sentiti libero di aprire una PR.

**Comment by lorenzo-asquini** [comment]
Ciao @Raffy142 e @GoukaMekkyaku. Anche se ancora non ho avuto tempo di considerare tutti i nuovi casi che si sono venuti a creare, ho aggiornato il codice per gestire il nuovo formato della pagina degli sconti e il caricamento dinamico. Ci sono ancora alcuni problemi, ma almeno ora è quasi totalmente utilizzabile

**Comment by Raffy142** [comment]
Vi ringrazio per le risposte esaustive, il problema è risolto grazie al vostro aiuto.
Siete grandiosi.
